services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8000"
    environment:
      DB_HOST: db
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_password
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PASSWORD: password_secure
      REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: laravel_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - laravel_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot_password"]
      timeout: 5s
      retries: 5
      interval: 10s
      start_period: 20s

  redis:
    image: redis:7.2-alpine
    container_name: laravel_redis
    restart: unless-stopped
    command: redis-server --requirepass password_secure
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "password_secure", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  laravel_db_data:
  redis_data: